class Central:
    def __init__(self, nombre, fullName, queries, file_name):
        self.nombre = nombre
        self.fullName = fullName
        self.queries = queries
        self.file_name = file_name

centrales = [
    Central(
        "IXTLA",
        "IXTLAHUACA",
        ['ASSETS IN IXTLAHUACA', 'SERVERS IN IXTLAHUACA', 'ALL NETWORK DEVICES IN IXTLAHUACA', 'PCs IN IXTLAHUACA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "TECA",
        "TECAMACHALCO",
        ['ASSETS IN TECAMACHALCO', 'SERVERS IN TECAMACHALCO', 'ALL NETWORK DEVICES IN TECAMACHALCO', 'PCs IN TECAMACHALCO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CIVAC",
        "CIVAC",
        ['ASSETS IN CIVAC', 'SERVERS IN CIVAC', 'ALL NETWORK DEVICES IN CIVAC', 'PCs IN CIVAC'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CUAUTI",
        "CUAUTITLAN",
        ['ASSETS IN CUAUTITLAN', 'SERVERS IN CUAUTITLAN', 'ALL NETWORK DEVICES IN CUAUTITLAN', 'PCs IN CUAUTITLAN'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "ECA",
        "ECATEPEC",
        ['ASSETS IN ECATEPEC', 'SERVERS IN ECATEPEC', 'ALL NETWORK DEVICES IN ECATEPEC', 'PCs IN ECATEPEC'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "POLANCO",
        "POLANCO",
        ['ASSETS IN POLANCO', 'SERVERS IN POLANCO', 'ALL NETWORK DEVICES IN POLANCO', 'PCs IN POLANCO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "POPOTLA",
        "POPOTLA",
        ['ASSETS IN POPOTLA', 'SERVERS IN POPOTLA', 'ALL NETWORK DEVICES IN POPOTLA', 'PCs IN POPOTLA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "REVO9",
        "REVOLUCION PACHUCA",
        ['ASSETS IN REVOLUCION PACHUCA', 'SERVERS IN REVOLUCION PACHUCA', 'ALL NETWORK DEVICES IN REVOLUCION PACHUCA', 'PCs IN REVOLUCION PACHUCA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "SAN_JER",
        "SAN JERONIMO",
        ['ASSETS IN SAN JERONIMO', 'SERVERS IN SAN JERONIMO', 'ALL NETWORK DEVICES IN SAN JERONIMO', 'PCs IN SAN JERONIMO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "TACUBA",
        "TACUBAYA",
        ['ASSETS IN TACUBAYA', 'SERVERS IN TACUBAYA', 'ALL NETWORK DEVICES IN TACUBAYA', 'PCs IN TACUBAYA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "TOLLO",
        "TOLLOCAN",
        ['ASSETS IN TOLLOCAN', 'SERVERS IN TOLLOCAN', 'ALL NETWORK DEVICES IN TOLLOCAN', 'PCs IN TOLLOCAN'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "URRAZA",
        "URRAZA",
        ['ASSETS IN URRAZA', 'SERVERS IN URRAZA', 'ALL NETWORK DEVICES IN URRAZA', 'PCs IN URRAZA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "XOCHI",
        "XOCHIMILCO",
        ['ASSETS IN XOCHIMILCO', 'SERVERS IN XOCHIMILCO', 'ALL NETWORK DEVICES IN XOCHIMILCO', 'PCs IN XOCHIMILCO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CARRAS",
        "CARRASCO",
        ['ASSETS IN CARRASCO', 'SERVERS IN CARRASCO', 'ALL NETWORK DEVICES IN CARRASCO', 'PCs IN CARRASCO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "TLAQUE",
        "TLAQUEPAQUE",
        ['ASSETS IN TLAQUEPAQUE', 'SERVERS IN TLAQUEPAQUE', 'ALL NETWORK DEVICES IN TLAQUEPAQUE', 'PCs IN TLAQUEPAQUE'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "URUAPAN",
        "URUAPAN",
        ['ASSETS IN URUAPAN', 'SERVERS IN URUAPAN', 'ALL NETWORK DEVICES IN URUAPAN', 'PCs IN URUAPAN'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "FRESNO",
        "FRESNO",
        ['ASSETS IN FRESNO', 'SERVERS IN FRESNO', 'ALL NETWORK DEVICES IN FRESNO', 'PCs IN FRESNO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "FUENTES",
        "FUENTES",
        ['ASSETS IN FUENTES', 'SERVERS IN FUENTES', 'ALL NETWORK DEVICES IN FUENTES', 'PCs IN FUENTES'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "MORELIA",
        "MORELIA",
        ['ASSETS IN MORELIA', 'SERVERS IN MORELIA', 'ALL NETWORK DEVICES IN MORELIA', 'PCs IN MORELIA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "VALLAR",
        "PTO VALLARTA",
        ['ASSETS IN PTO VALLARTA', 'SERVERS IN PTO VALLARTA', 'ALL NETWORK DEVICES IN PTO VALLARTA', 'PCs IN PTO VALLARTA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "GENERAL",
        "GENERAL",
        ['ASSETS IN GENERAL', 'SERVERS IN GENERAL', 'ALL NETWORK DEVICES IN GENERAL', 'PCs IN GENERAL'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R4",
        "R4",
        ['ASSETS IN R4', 'SERVERS IN R4', 'ALL NETWORK DEVICES IN R4', 'PCs IN R4'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R5",
        "R5",
        ['ASSETS IN R5', 'SERVERS IN R5', 'ALL NETWORK DEVICES IN R5', 'PCs IN R5'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R9",
        "R9",
        ['ASSETS IN R9', 'SERVERS IN R9', 'ALL NETWORK DEVICES IN R9', 'PCs IN R9'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "VALLEJO",
        "VALLEJO",
        ['ASSETS IN VALLEJO', 'SERVERS IN VALLEJO', 'ALL NETWORK DEVICES IN VALLEJO', 'PCs IN VALLEJO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "ANAHUAC",
        "ANAHUAC",
        ['ASSETS IN ANAHUAC', 'SERVERS IN ANAHUAC', 'ALL NETWORK DEVICES IN ANAHUAC', 'PCs IN ANAHUAC'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CARRANZ",
        "CARRANZA",
        ['ASSETS IN CARRANZA', 'SERVERS IN CARRANZA', 'ALL NETWORK DEVICES IN CARRANZA', 'PCs IN CARRANZA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "GUADALU",
        "GUADALUPE",
        ['ASSETS IN GUADALUPE', 'SERVERS IN GUADALUPE', 'ALL NETWORK DEVICES IN GUADALUPE', 'PCs IN GUADALUPE'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "LAREDO",
        "NUEVO LAREDO",
        ['ASSETS IN NUEVO LAREDO', 'SERVERS IN NUEVO LAREDO', 'ALL NETWORK DEVICES IN NUEVO LAREDO', 'PCs IN NUEVO LAREDO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "REVO4",
        "REVOLUCION",
        ['ASSETS IN REVOLUCION', 'SERVERS IN REVOLUCION', 'ALL NETWORK DEVICES IN REVOLUCION', 'PCs IN REVOLUCION'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "SAN_PED",
        "SAN PEDRO",
        ['ASSETS IN SAN PEDRO', 'SERVERS IN SAN PEDRO', 'ALL NETWORK DEVICES IN SAN PEDRO', 'PCs IN SAN PEDRO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R7",
        "R7",
        ['ASSETS IN R7', 'SERVERS IN R7', 'ALL NETWORK DEVICES IN R7', 'PCs IN R7'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R8",
        "R8",
        ['ASSETS IN R8', 'SERVERS IN R8', 'ALL NETWORK DEVICES IN R8', 'PCs IN R8'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "ARBOL",
        "ARBOL",
        ['ASSETS IN ARBOL', 'SERVERS IN ARBOL', 'ALL NETWORK DEVICES IN ARBOL', 'PCs IN ARBOL'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CACHA",
        "CACHANILLA",
        ['ASSETS IN CACHANILLA', 'SERVERS IN CACHANILLA', 'ALL NETWORK DEVICES IN CACHANILLA', 'PCs IN CACHANILLA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "BAHIA",
        "BAHIA",
        ['ASSETS IN BAHIA', 'SERVERS IN BAHIA', 'ALL NETWORK DEVICES IN BAHIA', 'PCs IN BAHIA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "LAPAZR1",
        "LAPAZR1",
        ['ASSETS IN LAPAZR1', 'SERVERS IN LAPAZR1', 'ALL NETWORK DEVICES IN LAPAZR1', 'PCs IN LAPAZR1'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "LOMAS",
        "LOMAS",
        ['ASSETS IN LOMAS', 'SERVERS IN LOMAS', 'ALL NETWORK DEVICES IN LOMAS', 'PCs IN LOMAS'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "OTAY",
        "OTAY",
        ['ASSETS IN OTAY', 'SERVERS IN OTAY', 'ALL NETWORK DEVICES IN OTAY', 'PCs IN OTAY'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R1",
        "R1",
        ['ASSETS IN R1', 'SERVERS IN R1', 'ALL NETWORK DEVICES IN R1', 'PCs IN R1'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R2",
        "R2",
        ['ASSETS IN R2', 'SERVERS IN R2', 'ALL NETWORK DEVICES IN R2', 'PCs IN R2'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R3",
        "R3",
        ['ASSETS IN R3', 'SERVERS IN R3', 'ALL NETWORK DEVICES IN R3', 'PCs IN R3'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R6",
        "R6",
        ['ASSETS IN R6', 'SERVERS IN R6', 'ALL NETWORK DEVICES IN R6', 'PCs IN R6'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CALINDA",
        "CALINDA",
        ['ASSETS IN CALINDA', 'SERVERS IN CALINDA', 'ALL NETWORK DEVICES IN CALINDA', 'PCs IN CALINDA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "EZAPATA",
        "EZAPATA",
        ['ASSETS IN EZAPATA', 'SERVERS IN EZAPATA', 'ALL NETWORK DEVICES IN EZAPATA', 'PCs IN EZAPATA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "GARMEN",
        "GARMENDIA",
        ['ASSETS IN GARMENDIA', 'SERVERS IN GARMENDIA', 'ALL NETWORK DEVICES IN GARMENDIA', 'PCs IN GARMENDIA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "INGENIE",
        "INGENIEROS",
        ['ASSETS IN INGENIEROS', 'SERVERS IN INGENIEROS', 'ALL NETWORK DEVICES IN INGENIEROS', 'PCs IN INGENIEROS'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "MOCHIS",
        "MOCHIS",
        ['ASSETS IN MOCHIS', 'SERVERS IN MOCHIS', 'ALL NETWORK DEVICES IN MOCHIS', 'PCs IN MOCHIS'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "OBREGON",
        "OBREGON",
        ['ASSETS IN OBREGON', 'SERVERS IN OBREGON', 'ALL NETWORK DEVICES IN OBREGON', 'PCs IN OBREGON'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "SABALO",
        "SABALO",
        ['ASSETS IN SABALO', 'SERVERS IN SABALO', 'ALL NETWORK DEVICES IN SABALO', 'PCs IN SABALO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "BONAMPA",
        "BONAMPAK",
        ['ASSETS IN BONAMPAK', 'SERVERS IN BONAMPAK', 'ALL NETWORK DEVICES IN BONAMPAK', 'PCs IN BONAMPAK'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CASCADA",
        "CASCADA",
        ['ASSETS IN CASCADA', 'SERVERS IN CASCADA', 'ALL NETWORK DEVICES IN CASCADA', 'PCs IN CASCADA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "JUAREZ",
        "JUAREZ",
        ['ASSETS IN JUAREZ', 'SERVERS IN JUAREZ', 'ALL NETWORK DEVICES IN JUAREZ', 'PCs IN JUAREZ'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "MONTEJO",
        "MONTEJO",
        ['ASSETS IN MONTEJO', 'SERVERS IN MONTEJO', 'ALL NETWORK DEVICES IN MONTEJO', 'PCs IN MONTEJO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "PLAZA",
        "PLAZA",
        ['ASSETS IN PLAZA', 'SERVERS IN PLAZA', 'ALL NETWORK DEVICES IN PLAZA', 'PCs IN PLAZA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "MTY",
        "MONTERREY",
        ['ASSETS IN MONTERREY', 'SERVERS IN MONTERREY', 'ALL NETWORK DEVICES IN MONTERREY', 'PCs IN MONTERREY'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "GDL",
        "GUADALAJARA",
        ['ASSETS IN GUADALAJARA', 'SERVERS IN GUADALAJARA', 'ALL NETWORK DEVICES IN GUADALAJARA', 'PCs IN GUADALAJARA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "CARSO",
        "CARSO",
        ['ASSETS IN CARSO', 'SERVERS IN CARSO', 'ALL NETWORK DEVICES IN CARSO', 'PCs IN CARSO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "L_ALB",
        "LAGO ALBERTO",
        ['ASSETS IN LAGO ALBERTO', 'SERVERS IN LAGO ALBERTO', 'ALL NETWORK DEVICES IN LAGO ALBERTO', 'PCs IN LAGO ALBERTO'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "ECALIN",
        "ECALINDA",
        ['ASSETS IN ECALINDA', 'SERVERS IN ECALINDA', 'ALL NETWORK DEVICES IN ECALINDA', 'PCs IN ECALINDA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "ECHIHUA",
        "ECHIHUAHUA",
        ['ASSETS IN ECHIHUAHUA', 'SERVERS IN ECHIHUAHUA', 'ALL NETWORK DEVICES IN ECHIHUAHUA', 'PCs IN ECHIHUAHUA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "ETIJUA",
        "ETIJUANA",
        ['ASSETS IN ETIJUANA', 'SERVERS IN ETIJUANA', 'ALL NETWORK DEVICES IN ETIJUANA', 'PCs IN ETIJUANA'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R6OFCOR",
        "R6OFCOR",
        ['ASSETS IN R6OFCOR', 'SERVERS IN R6OFCOR', 'ALL NETWORK DEVICES IN R6OFCOR', 'PCs IN R6OFCOR'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R7OFCOR",
        "R7OFCOR",
        ['ASSETS IN R7OFCOR', 'SERVERS IN R7OFCOR', 'ALL NETWORK DEVICES IN R7OFCOR', 'PCs IN R7OFCOR'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
    Central(
        "R8OFCOR",
        "R8OFCOR",
        ['ASSETS IN R8OFCOR', 'SERVERS IN R8OFCOR', 'ALL NETWORK DEVICES IN R8OFCOR', 'PCs IN R8OFCOR'],
        ['TOTAL_ASSETS', 'SERVERS', 'NET_DEV', 'PCs'],
    ),
]
